import './globals.css';

import { Source_Serif_Pro } from 'next/font/google';

const Font = Source_Serif_Pro({
  weight: ['200', '300', '400', '600', '700', '900'],
  style: 'normal',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={Font.className}>{children}</body>
    </html>
  );
}
