import { Source_Serif_Pro } from 'next/font/google'

import { AppContextProvider } from './components/context'
import './globals.css'

const Font = Source_Serif_Pro({
  weight: ['200', '300', '400', '600', '700', '900'],
  style: 'normal',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Dictionary App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <AppContextProvider>
      <html lang="en">
        <body className={Font.className}>{children}</body>
      </html>
    </AppContextProvider>
  )
}
